[project]
name = "dlgen-ai-quiz-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=5.0.1",
    "faiss-cpu>=1.14.3",
    "ipykernel>=7.3.0",
    "jupyter-client>=8.9.1",
    "langchain-text-splitters>=1.1.2",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "nbformat>=5.10.4",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "peft>=0.20.0",
    "protobuf>=7.35.1",
    "pyarrow>=25.0.0",
    "pypdf>=6.14.2",
    "reportlab>=5.0.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.6.1",
    "sentencepiece>=0.2.2",
    "tiktoken>=0.13.0",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
    "transformers>=5.14.1",
    "wandb>=0.28.1",
    "wikipedia>=1.4.0",
]
